### ISSUE TITLE
bug: Markdown is being interpreted incorrectly.

### ISSUE THREAD

**Issue by saraid** [dwmkerr/effective-shell#255]
I haven't tracked down the root of the issue, but this line

https://github.com/dwmkerr/effective-shell/blob/4202a0a7ef9e2e61cb6107d007e27e5266dc2267/docs/03-manipulating-text/13-regex-essentials/index.md?plain=1#L121

is being interpreted incorrectly by Docusaurus. Specifically, `_@yahoo.com_` is generating a non-italicized, valid `_@yahoo.com` email address as a mailto link. GFM is handling it fine, though.

It's a very minor issue, but it detracts from the point of the sentence. I can imagine fixing it by choosing a different bit of formatting, or perhaps adding a leading space, but I'm not familiar with Docusaurus' quirks, so it's hard to advise a solution.

**Comment by dwmkerr** [comment]
Thanks @saraid - good spot! I've changed these fragments to use code formatting which I think is more consistent with what we have in the rest of the chapter, and fixes the formatting issues. Thanks for raising this!

**Comment by dwmkerr** [comment]
@all-contributors please add @saraid for review
