### ISSUE TITLE
question on the shell scripting, loops chapter

### ISSUE THREAD

**Issue by nosarthur** [dwmkerr/effective-shell#269]
In the C style loops section, there is this paragraph.

> This loop structure uses three arithmetic expressions to run the loop. The first is in 'initialise' expression, this is typically used to setup the initial state of the loop. The second is the 'conditional' expression, this is used to check whether the loop is complex. The third is the 'iterate' expression, this is evaluated after the loop commands are completed.

Why is `complex` used here? Is it a typo?

**Comment by dwmkerr** [comment]
oh well spotted - it should be 'complete' - fixing now!
